# Generated by Django 5.2.5 on 2025-08-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Token_System', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('doctor', 'Doctor'), ('patient', 'patient')], default='staff', max_length=20),
        ),
    ]
