# Generated by Django 5.2.5 on 2025-08-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Token_System', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
